### PR TITLE
mounts.d: Allow more flexibility with flags to support mounting in unprivileged containers

### PR DESCRIPTION
**Pull request by livingsilver94**

### CODE REVIEW

**Comment by ermo** [comment]
This changes the interface so needs a justification for future reference.

**Comment by livingsilver94** [comment]
I'm gonna change PR's title (as the current one doesn't reflect the scope anymore) and add error handling to my latest commit. Marking as draft as a consequence.

**Comment by ermo** [comment]
How are you linking with libmount? Shared linking?

Do we need to link statically and/or vendor libmount?

**Comment by livingsilver94** [comment]
It's statically linked. Dub defaults to static linking per se, and meson uses static linking because the final library is declared with `static_library`.

Arch provides libmount statically linked. The usual approach is to use the system library, then fall back to the vendored when when not available. What do you think?

**Comment by ermo** [comment]
> The usual approach is to use the system library, then fall back to the vendored when when not available. What do you think?

Sounds good to me.

**Comment by ermo** [comment]
@livingsilver94:

Thanks for taking the time to test with various packages, including local repo.

LGTM!

**Pull request merged**
